
spring:
  application:
    name: user-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    eureka:
    client:
        fetchRegistry: true
        

    app:
  id: ${random.uuid}